name: Sync & Purge Directories

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  deploy-and-purge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Cleanup Git Files
        run: rm -rf .git .github
      - name: Install B2 CLI
        run: pip install b2
      # ========================================================
      # 阶段 1: 存储桶同步 (Storage Sync)
      # ========================================================
      - name: Sync Files to B2
        env:
          B2_KEY_ID: ${{ secrets.B2_KEY_ID }}
          B2_APP_KEY: ${{ secrets.B2_APP_KEY }}
          B2_BUCKET_NAME: ${{ secrets.B2_BUCKET_NAME }}
        run: |
          # 登录 B2
          b2 account authorize $B2_KEY_ID $B2_APP_KEY > /dev/null
          rm -rf .git .github
          b2 sync --threads 10 . b2://$B2_BUCKET_NAME/pjsk/sekai-db/jp
          
      - name: Install Rclone
        run: |
          curl -O https://downloads.rclone.org/rclone-current-linux-amd64.zip
          unzip -q rclone-current-linux-amd64.zip
          
          cd rclone-*-linux-amd64
          sudo cp rclone /usr/bin/
          sudo chown root:root /usr/bin/rclone
          sudo chmod 755 /usr/bin/rclone
          cd ..
          
          rm -rf rclone-*-linux-amd64* rclone-current-linux-amd64.zip
          rclone version
        
      - name: Sync to R2
        env:
          RCLONE_CONFIG_R2_TYPE: s3
          RCLONE_CONFIG_R2_PROVIDER: Cloudflare
          RCLONE_CONFIG_R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          RCLONE_CONFIG_R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          RCLONE_CONFIG_R2_ENDPOINT: https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com
        run: |
          rclone sync . r2:${{ secrets.R2_BUCKET_NAME }}/pjsk/sekai-db/jp \
            --verbose \
            --transfers 32 \
            --checkers 64 \
            --exclude ".git/**" \
            --exclude ".github/**"
      - name: Install COSCMD
        run: pip install coscmd

      - name: Sync to Tencent OSS
        env:
          SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
          SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
          BUCKET: ${{ secrets.OSS_BUCKET }}
          REGION: ${{ secrets.OSS_REGION }}
        run: |
          coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION
          # 上传并清理远端多余文件
          coscmd upload -r . pjsk/sekai-db/jp/ --delete --ignore "*.py"

      # ========================================================
      # 阶段 2: CDN 缓存清理 (Directory Purge)
      # ========================================================
     

      - name: Purge Cloudflare Prefix
        env:
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          B2_BUCKET_NAME: ${{ secrets.B2_BUCKET_NAME }}
        shell: python
        run: |
          import os, requests, json
          bucket_name = os.environ["B2_BUCKET_NAME"]

          targets = [
            f"cdn.8823.eu.org/file/{bucket_name}/pjsk/sekai-db/jp/"
          ]

          zone_id = os.environ["CF_ZONE_ID"]
          token = os.environ["CF_API_TOKEN"]
          url = f"https://api.cloudflare.com/client/v4/zones/{zone_id}/purge_cache"
          
          headers = {
              "Authorization": f"Bearer {token}",
              "Content-Type": "application/json"
          }
          
          payload = { "prefixes": targets }
          
          try:
              resp = requests.post(url, headers=headers, json=payload)
              print(f"Status: {resp.status_code}")
              print(resp.text)
          except Exception as e:
              print(f"Error: {e}")

      # - name: Purge Tencent EdgeOne Prefix
        # env:
          # TENCENTCLOUD_EO_SECRET_ID: ${{ secrets.RESONACN_TENCENT_SECRET_ID }}
          # TENCENTCLOUD_EO_SECRET_KEY: ${{ secrets.RESONACN_TENCENT_SECRET_KEY }}
          # TEO_ZONE_ID: ${{ secrets.TEO_ZONE_ID }}
        # shell: python
        # run: |
          # import os, hashlib, hmac, json, time
          # from datetime import datetime
          # try: from http.client import HTTPSConnection
          # except ImportError: from httplib import HTTPSConnection

          # targets = [
             # "https://cdn.resona.cn/sekai-db/jp/"
          # ]

          # secret_id = os.environ.get("TENCENTCLOUD_EO_SECRET_ID")
          # secret_key = os.environ.get("TENCENTCLOUD_EO_SECRET_KEY")
          # zone_id = os.environ.get("TEO_ZONE_ID")
          # host = "teo.tencentcloudapi.com"
          # timestamp = int(time.time())
          # date = datetime.utcfromtimestamp(timestamp).strftime("%Y-%m-%d")

          # payload = json.dumps({
              # "ZoneId": zone_id,
              # "Type": "purge_prefix", 
              # "Method": "delete",
              # "Targets": targets
          # })

          # def sign(key, msg): return hmac.new(key, msg.encode("utf-8"), hashlib.sha256).digest()
          # canonical_headers = "content-type:application/json; charset=utf-8\nhost:%s\nx-tc-action:createpurgetask\n" % host
          # hashed_payload = hashlib.sha256(payload.encode("utf-8")).hexdigest()
          # canonical_req = "POST\n/\n\n" + canonical_headers + "content-type;host;x-tc-action\n" + hashed_payload
          # cred_scope = date + "/teo/tc3_request"
          # string_to_sign = "TC3-HMAC-SHA256\n" + str(timestamp) + "\n" + cred_scope + "\n" + hashlib.sha256(canonical_req.encode("utf-8")).hexdigest()
          # secret_date = sign(("TC3" + secret_key).encode("utf-8"), date)
          # signature = hmac.new(sign(sign(secret_date, "teo"), "tc3_request"), string_to_sign.encode("utf-8"), hashlib.sha256).hexdigest()
          # auth = "TC3-HMAC-SHA256 Credential=%s/%s, SignedHeaders=content-type;host;x-tc-action, Signature=%s" % (secret_id, cred_scope, signature)

          # print(f"Purging EdgeOne Prefixes: {targets}")
          # conn = HTTPSConnection(host)
          # conn.request("POST", "/", headers={"Authorization": auth, "Content-Type": "application/json; charset=utf-8", "Host": host, "X-TC-Action": "CreatePurgeTask", "X-TC-Timestamp": str(timestamp), "X-TC-Version": "2022-09-01"}, body=payload)
          # print(conn.getresponse().read().decode('utf-8'))

      - name: Purge Aliyun ESA Directory
        env:
          ALI_ID: ${{ secrets.ALI_ID }}
          ALI_SECRET: ${{ secrets.ALI_SECRET }}
          ALI_SITE_ID: ${{ secrets.ALI_SITE_ID }}
          ALI_DOMAIN: ${{ secrets.ALI_DOMAIN }}
        run: |
          pip install alibabacloud_esa20240910==2.34.0 alibabacloud_tea_openapi alibabacloud_tea_util

          python -c "
          import os
          import sys
          from alibabacloud_esa20240910.client import Client as EsaClient
          from alibabacloud_esa20240910 import models as esa_models
          from alibabacloud_tea_openapi import models as open_api_models
          from alibabacloud_tea_util import models as util_models

          try:
              config = open_api_models.Config(
                  access_key_id=os.environ['ALI_ID'],
                  access_key_secret=os.environ['ALI_SECRET']
              )
              config.endpoint = 'esa.cn-hangzhou.aliyuncs.com'
              client = EsaClient(config)

              domain = os.environ['ALI_DOMAIN']
              target_url = f'https://{domain}/sekai-db/jp/'
              print(f'Target URL: {target_url}')

              request = esa_models.PurgeCachesRequest(
                  site_id=int(os.environ['ALI_SITE_ID']),
                  type='directory',
                  content=[target_url]
              )

              runtime = util_models.RuntimeOptions()
              resp = client.purge_caches_with_options(request, runtime)
              
              print('Aliyun ESA Purge Success!')
              print(f'RequestId: {resp.body.request_id}')

          except Exception as error:
              print(f'Aliyun ESA Failed: {error}')
              if hasattr(error, 'message'):
                  print(error.message)
              sys.exit(1)
          "
