name: Trigger Private Sync

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - '**.json'
jobs:
  notify-private-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Private Repository
        run: |
          TARGET_REPO="${{ secrets.PRIVATE_REPO_NAME }}"
          curl -X POST https://api.github.com/repos/$TARGET_REPO/dispatches \
          -H 'Accept: application/vnd.github.v3+json' \
          -H 'Authorization: token ${{ secrets.PRIVATE_REPO_PAT }}' \
          --data '{"event_type": "pjsekai_update"}'
